### PR TITLE
Added configurable java options

### PR DESCRIPTION
**Pull request by Nekroze**
This just adds an additional environment variable `JAVA_OPTS` that has some minor tweaks by default but allows for them to be over-ridden by the end user.

### CODE REVIEW

**Comment by Nekroze** [comment]
Sorry for the messy spam of pull requests last time. they also included a typo. fixed now and should be all good.

**Comment by tboerger** [comment]
Thank you, hopefully I can do the rebase on mobile network, currently I'm on vacation. If I can't do it through that connection it got to wait until monday :)

**Comment by Nekroze** [comment]
All good mate. For now I have put my fork up on docker hub to use and will take it down once this is pulled in.

Enjoy the vacation!

**Comment by Nekroze** [comment]
Just realised this was pulled in. are you able to drop a note in this pull request once it is rebased to the other versions so i know when to take mine down?

**Comment by tboerger** [comment]
Sure, I will send you a ping through this pr :)

**Comment by tboerger** [comment]
@Nekroze I have pushed the changes for all forge versions. Sorry for the delay...

**Comment by Nekroze** [comment]
@tboerger Awesome. Will take my version off of the docker registery.

**Comment by tboerger** [comment]
:+1:
I'm happy that there are other people using my container :)

**Pull request merged**
